version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    ports:
      - "3008:3008"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/userdb
    depends_on:
      - mongodb

  property-service:
    build:
      context: ./property-service
      dockerfile: Dockerfile
    container_name: property-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/propertydb
    depends_on:
      - mongodb

  maintenance-service:
    build:
      context: ./maintenance-service
      dockerfile: Dockerfile
    container_name: maintenance-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/maintenancedb
    depends_on:
      - mongodb

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/notificationdb
    depends_on:
      - mongodb

  communication-service:
    build:
      context: ./communication-service
      dockerfile: Dockerfile
    container_name: communication-service
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/communicationdb
    depends_on:
      - mongodb

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/paymentdb
      - MPESA_CONSUMER_KEY=${MPESA_CONSUMER_KEY}
      - MPESA_CONSUMER_SECRET=${MPESA_CONSUMER_SECRET}
      - MPESA_SHORTCODE=${MPESA_SHORTCODE}
      - MPESA_PASSKEY=${MPESA_PASSKEY}
      - BASE_URL=http://localhost:3005
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
