version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/userdb
    depends_on:
      - mongodb

  property-service:
    build:
      context: ./property-service
      dockerfile: Dockerfile
    container_name: property-service
    restart: unless-stopped
    ports:
      - "3003:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/propertydb
    depends_on:
      - mongodb


volumes:
  mongodb_data:
    driver: local
