# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Install dev dependencies (example: nodemon for auto-reloading)
RUN npm install --only=development
RUN npm install nodemon -g

# Bundle app source
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Command to run your app using nodemon for development
CMD ["nodemon", "app.js"]
